### ISSUE TITLE
viewDidAppear

### ISSUE THREAD

**Issue by onmyway133** [Yalantis/PullToMakeSoup#10]
Hi, thanks for such wonderful animation.

I think we need to mention that it only work when the size is determined. Like in `viewDidAppear` as in the example project

```
override func viewDidAppear(animated: Bool) {
        super.viewDidAppear(animated)

        tableView.addPullToRefresh(PullToMakeSoup(), action: {
            let delayTime = dispatch_time(DISPATCH_TIME_NOW,
                Int64(5 * Double(NSEC_PER_SEC)))
            dispatch_after(delayTime, dispatch_get_main_queue()) { [unowned self] in
                self.tableView.endRefreshing()
            }
        })
    }
```

**Comment by EgorSobko** [comment]
@onmyway133 Hi, thank you for such helpful note, we'll think about updating Usage guide in README file, so that people won't have misunderstandings with framework usage.
