### ISSUE TITLE
Animation slides up and hides after releasing the pull handle

### ISSUE THREAD

**Issue by nimblemindsapps** [Yalantis/PullToMakeSoup#11]
I have implemented the code as suggested. Everything works fine except that when I release the pull, the tableview cells and animation both slides up and animation hides behind the navigation bar. How can I keep the animation on screen until it is completed and then slide it up to disappear from the screen?

**Comment by EgorSobko** [comment]
@nimblemindsapps Hi, thanks for using! Could you please check if 'Adjust Scroll View Insets' selected in your view controller? If NO, then try to select it and then tell us if your issue still exists.

**Comment by nimblemindsapps** [comment]
you're welcome!
Adjust Scroll View Insets was already selected in my view controller and I was having this issue. When I unchecked it, the animation worked fine as expected but then my tableview, which is pinned to the top layout guide moves behind the navigation bar. I can't pin it below the navbar because i am using HidingNavigationBarManager from other libary. Is there any other manual way I can make the scroll view insets adjusted only for refresher?

**Comment by EgorSobko** [comment]
@nimblemindsapps Could you please try one more thing, on storyboard pick your controller and deselect 'Under Top Bars' checkbox. Please provide us information about the result, thanks.

**Comment by nimblemindsapps** [comment]
I did try that and again animations works fine and holds onto the screen but the tableview is now pinned below the navbar (which i don't want as my navbar collapses on scroll). I am using this library for hiding navbar https://github.com/tristanhimmelman/HidingNavigationBar. 

Here is the screenshot of my VC while I pull to refresh:
![simulator screen shot nov 18 2015 2 43 11 pm](https://cloud.githubusercontent.com/assets/10893602/11237739/74c07172-8e03-11e5-86bf-4783deb14c1f.png)

and here this is what happens when I scroll up. tableview layout doesnt adjust and I get the black bg at the place of navbar
![simulator screen shot nov 18 2015 2 48 52 pm](https://cloud.githubusercontent.com/assets/10893602/11237784/adcde300-8e03-11e5-95fd-ee171f990707.png)

**Comment by EgorSobko** [comment]
@nimblemindsapps We've made some tests where we had this black bar as yours and after some investigations we found a solution like this:
- do not install as a pod 'HidingNavigationBar'. Copy it to your app folder;
- in lifecycle functions of your VC do not call methods for 'HidingNavigationBar';
- in HidingNavigationBar's init(viewController: UIViewController, scrollView: UIScrollView) method comment/delete updateContentInsets();
- VC setting in storyboard: Adjust Scroll View Insets - YES, Under Top Bars - YES.

After all this actions everything works fine in Portrait mode, but I can't say that this solution would relsove your issue entirely. I'm looking forward for your feedback if this helped you.

**Comment by nimblemindsapps** [comment]
All the above points make it work! For the extension view of navigation bar, I had to put that in viewDidAppear instead of viewDidLoad to make it  work. Than you so much for your help! :) Here is the result:
![simulator screen shot nov 19 2015 4 58 37 pm](https://cloud.githubusercontent.com/assets/10893602/11270216/d386f470-8ede-11e5-84cd-0796dd5b187c.png)
