### ISSUE TITLE
Adding the framework to app

### ISSUE THREAD

**Issue by y0dev** [Yalantis/PullToMakeSoup#12]
Whenever I add the import statement to my bridging header it gives me an error reading saying that the files could not be found. Any help please?

**Comment by EgorSobko** [comment]
@juniorProgrammer Could you pls describe more extendedly, why you are importing framework to your bridging header?

**Comment by maksym-letiushov** [comment]
@juniorProgrammer also please check this link https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html
Hope it helps

**Comment by y0dev** [comment]
@maximletushov @EgorSobko It gives me a error in the import statement saying that cannot load underlying module for 'PullToMakeSoup'

**Comment by juniorProgrammer** [comment]
@EgorSobko so when I download the zip file and try to build and run the original app. The compiler stops it and goes to the PullToMakeSoup file and in the import statement there is an error saying that the PullToRefresh can't be found

**Comment by y0dev** [comment]
@EgorSobko @maximletushov  so I figured it out why I wasn't working but now that it
