### ISSUE TITLE
Cocoapod update problems.

### ISSUE THREAD

**Issue by laud** [Yalantis/PullToMakeSoup#14]
Currently trying to upgrade from v1.0 to v1.1. When I try do a build, I get the following error: Could not build module 'PullToMakeSoup'. I am trying to import into an Objective-C controller. When I inspect the selectors, it does reveal the appropriate -Swift.h file, but the build continues to fail. I am using `use_frameworks!` in my .Podfile.

Any ideas or suggestions? I have tried to clean, rebuild, and clear out Derived Data to no avail.

**Comment by KaterynaZaikina** [comment]
@laud I tried to reproduce it but didn't reveal any problems. Check your Podfile and Podfile.lock for right version (v.1.1) of Pod. Also check how you import it into your Objective-C controller - #import "PullToMakeSoup.h"
