### ISSUE TITLE
Not updating properly for device rotation

### ISSUE THREAD

**Issue by mlvea** [Yalantis/PullToMakeSoup#15]
If you rotate the device while making the soup UI not updates properly.

**Comment by KaterynaZaikina** [comment]
@madnik Thank you for interest. Yes, it has such problem with rotation and we will give attention to fixing this bug.

**Comment by serejahh** [comment]
The pull to refresh is too high and on iPhone 4, 5 it can't be triggered. That's the reason why we don't support landscape orientation
