### ISSUE TITLE
warning: Could not find remote branch 1.4.0 to clone. fatal: Remote branch 1.4.0 not found in upstream origin

### ISSUE THREAD

**Issue by zafar007** [Yalantis/PullToMakeSoup#19]
Zafars-iMac:podinstall ZafarAhmad$ pod install
Analyzing dependencies
Downloading dependencies
Installing PullToMakeFlight (1.1.2)
Installing PullToMakeSoup (1.2)
Installing PullToRefresher (1.4.0)

[!] Error installing PullToRefresher
[!] /usr/bin/git clone https://github.com/Yalantis/PullToRefresh.git /var/folders/89/9pzfjxd50bs5_hy39qqm3m8r0000gn/T/d20160804-2979-vq368o --template= --single-branch --depth 1 --branch 1.4.0

Cloning into '/var/folders/89/9pzfjxd50bs5_hy39qqm3m8r0000gn/T/d20160804-2979-vq368o'...
warning: Could not find remote branch 1.4.0 to clone.
fatal: Remote branch 1.4.0 not found in upstream origin

**This is my Podfile**
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

inhibit_all_warnings!

target 'podinstall' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for podinstall

  target 'podinstallTests' do
    pod 'PullToMakeFlight'
    pod 'PullToMakeSoup'

```
# Pods for testing
```

  end

  target 'podinstallUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

**Comment by serejahh** [comment]
Pushed the tag. Now everything is ok. Thanks for reporting the issue
