### ISSUE TITLE
Ambiguous use of 'init'

### ISSUE THREAD

**Issue by Jasperav** [Yalantis/PullToMakeSoup#23]
let refresher = PullToMakeSoup() When I add this somewhere in my code, I get that error. Yes I included the import PullToMakeSoup and PullToRefresh. Also, tableView.endRefreshing() is saying: Missing argument for ' at'. How can I fix this?

**Comment by bablu-joshi** [comment]
Same issue

**Comment by bablu-joshi** [comment]
Use this instead !
        self.myTableView.addPullToRefresh(PullToMakeSoup(at: .top)) { }

**Comment by bablu-joshi** [comment]
let refresher = PullToMakeSoup(at: .top)
