### ISSUE TITLE
Can't find Soupview

### ISSUE THREAD

**Issue by alexliubj** [Yalantis/PullToMakeSoup#4]
public class PullToMakeSoup: PullToRefresh {
    public convenience init() {

```
    let refreshView =  NSBundle(identifier: "Yalantis.PullToMakeSoup")!.loadNibNamed("SoupView", owner: nil, options: nil).first as! SoupView
    let animator =  SoupAnimator(refreshView: refreshView)
    self.init(refreshView: refreshView, animator: animator)
}
```

}

fatal error: unexpectedly found nil while unwrapping an Optional value

**Comment by EMidee66** [comment]
I am having the same issue. @alexliubj Did you find a solution?

**Comment by alexliubj** [comment]
create new project and use this in podfile. Re-import everything back

**Comment by alexliubj** [comment]
create new project and use this in podfile. Re-import everything back

On Sun, Sep 13, 2015 at 7:35 AM, EMidee66 notifications@github.com wrote:

> I am having the same issue. @alexliubj https://github.com/alexliubj Did
> you find a solution?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Yalantis/PullToMakeSoup/issues/4#issuecomment-139862616
> .

## 

Alex.Liu

**Comment by dcflow** [comment]
Thank you @alexliubj for your help.
