### ISSUE TITLE
swift 2.0 Expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions

### ISSUE THREAD

**Issue by alexliubj** [Yalantis/PullToMakeSoup#7]
Pulltomakesoup.swift file and location has this error:

 let progressWithOffset: (Double, Double) -> Double = { offset, progress in
            return progress < offset ? 0 : Double((progress - offset) \* 1 / (1 - offset))

**Comment by alexliubj** [comment]
Resolving this with replacing it by a function 

 func progressWithOffset(offset:Double, progress: Double) -> Double
    {
        return progress < offset ? 0 : Double((progress - offset) \* 1 / (1 - offset))
    }

**Comment by sekouperry** [comment]
Thanks for the fix.

**Comment by jiaowochunge** [comment]
seems like hasn't applied yet. the solution above has a little problem.the second parameter should be omitted.just add '_'

func progressWithOffset(offset:Double, _ progress: Double) -> Double
{
return progress < offset ? 0 : Double((progress - offset) \* 1 / (1 - offset))
}

**Comment by Art3mS1d** [comment]
Thanks, @alexliubj  and @jiaowochunge . Now fix in the master. Pod also updated
